# Generated by Django 4.1.2 on 2023-02-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_news_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_active',
        ),
        migrations.AddField(
            model_name='chat',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
